//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppConsole.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_venta
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_venta()
        {
            this.detalleVenta1 = new HashSet<detalleVenta>();
            this.detalleVenta2 = new HashSet<detalleVenta>();
            this.detalleVenta3 = new HashSet<detalleVenta>();
        }
    
        public int idVenta { get; set; }
        public Nullable<int> idDocumento { get; set; }
        public Nullable<int> iDCliente { get; set; }
        public Nullable<int> iDUsuario { get; set; }
        public Nullable<decimal> totalVenta { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
    
        public virtual detalleVenta detalleVenta { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<detalleVenta> detalleVenta1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<detalleVenta> detalleVenta2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<detalleVenta> detalleVenta3 { get; set; }
        public virtual tb_cliente tb_cliente { get; set; }
        public virtual tb_documento tb_documento { get; set; }
        public virtual usuario usuario { get; set; }
    }
}
