//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ferreteria_I.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class usuario
    {
        public int id_usuario { get; set; }
        public string nombre { get; set; }
        public string apellido { get; set; }
        public Nullable<int> id_rol { get; set; }
        public string usuario1 { get; set; }
        public string estado { get; set; }
        public string clave { get; set; }
        public string direccion { get; set; }
        public Nullable<int> id_departamento { get; set; }
        public Nullable<int> id_municipio { get; set; }
        public Nullable<int> telefono { get; set; }
    
        public virtual departamento departamento { get; set; }
        public virtual municipio municipio { get; set; }
        public virtual rol rol { get; set; }
    }
}
